- hosts: web
  become: yes
  tasks:

    - name: Pull image
      command: docker pull docker.io/snowjohn0101200/myapp:latest

    - name: Stop old container
      command: docker rm -f myapp
      ignore_errors: yes

    - name: Run container
      command: docker run -d -p 80:80 --name myapp docker.io/snowjohn0101200/myapp:latest
