name: CI-CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build Image
      run: docker build -t myapp .

    - name: Tag Image
      run: docker tag myapp snowjohn0101200/myapp:latest

    - name: Login to DockerHub
      run: echo "${{ secrets.docker_key }}" | docker login -u snowjohn0101200 --password-stdin

    - name: Push Image
      run: docker push snowjohn0101200/myapp:latest


    - name: Setup SSH
      run: |
         mkdir -p ~/.ssh
         echo "${{ secrets.EC2_GITREPO }}" > ~/.ssh/id_rsa
         chmod 600 ~/.ssh/id_rsa
         ssh-keyscan -H 13.61.8.8 >> ~/.ssh/known_hosts

    - name: Pull and run Container
      run: ansible-playbook -i inventory deploy.yml
